# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0002_colorextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aanmelding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('geslacht', models.CharField(choices=[('M', 'Jongen'), ('F', 'Meisje')], default=None, max_length=1)),
                ('klas', models.CharField(choices=[('1', 'Groep 1'), ('2', 'Groep 2'), ('3', 'Groep 3'), ('4', 'Groep 4'), ('5', 'Groep 5'), ('6', 'Groep 6'), ('7', 'Groep 7'), ('8', 'Groep 8')], max_length=1)),
                ('adres', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('tel1', models.CharField(max_length=100)),
                ('tel2', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('De Sleutelaar', 'De Sleutelaar'), ('De Toermalijn', 'De Toermalijn'), ('Franciscusschool', 'Franciscusschool'), ('Mariaschool', 'Mariaschool'), ('De Piramide', 'De Piramide')], default=None, max_length=100)),
                ('allergien', models.TextField()),
                ('groepsmaatje', models.CharField(max_length=100)),
                ('groepsmaatje_school', models.CharField(max_length=100)),
                ('overnachting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vrijwilliger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100)),
                ('tussenvoegsel', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=100)),
                ('geboortedatum', models.DateField()),
                ('tel', models.CharField(max_length=50)),
                ('stage', models.BooleanField()),
                ('eigen_kind', models.CharField(max_length=100)),
                ('opmerkingen', models.TextField()),
                ('dagen', models.ManyToManyField(to='mvs.Dag')),
                ('taken', models.ManyToManyField(to='mvs.Taak')),
            ],
        ),
    ]
