# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0004_auto_20180417_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanmelding',
            name='heeft_betaald',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='inschrijf_datum',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aanmelding',
            name='opmerkingen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aanmelding',
            name='overnachting',
            field=models.BooleanField(default=False),
        ),
    ]
