# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0005_auto_20180417_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanmelding',
            name='school',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
