# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0006_auto_20180418_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aanmelding',
            options={'ordering': ['-inschrijf_datum'], 'verbose_name_plural': 'Aanmeldingen'},
        ),
        migrations.AddField(
            model_name='vrijwilliger',
            name='adres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vrijwilliger',
            name='ehbo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vrijwilliger',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vrijwilliger',
            name='geslacht',
            field=models.CharField(choices=[('M', 'Man'), ('V', 'Vrouw')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vrijwilliger',
            name='postcode',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vrijwilliger',
            name='tel2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vrijwilliger',
            name='woonplaats',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
