# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0007_auto_20181010_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrijwilliger',
            name='aanmelding_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vrijwilliger',
            name='tel2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
