# Generated by Django 2.2.12 on 2020-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0010_auto_20200405_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='aanmelding',
            name='postcode',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='woonplaats',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
