# Generated by Django 2.2.12 on 2020-05-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0011_auto_20200405_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aanmelding',
            name='allergien',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='geslacht',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='groepsmaatje',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='groepsmaatje_school',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='heeft_betaald',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='klas',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='overnachting',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='school',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='tel1',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='voornaam',
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind1_leeftijd',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind1_naam',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind2_leeftijd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind2_naam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind3_leeftijd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind3_naam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind4_leeftijd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind4_naam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind5_leeftijd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind5_naam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind6_leeftijd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kind6_naam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='kinderen',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='tel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aanmelding',
            name='tel2',
            field=models.CharField(max_length=100),
        ),
    ]
