# Generated by Django 2.2.12 on 2020-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0012_auto_20200517_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanmelding',
            name='tel2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
