# Generated by Django 3.2 on 2022-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0015_auto_20200521_1705'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM mvs_aanmelding"),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind1_leeftijd',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind1_naam',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind2_leeftijd',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind2_naam',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind3_leeftijd',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind3_naam',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind4_leeftijd',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind4_naam',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind5_leeftijd',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind5_naam',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind6_leeftijd',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kind6_naam',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='kinderen',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='team_naam',
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='tel',
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='allergien',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='geslacht',
            field=models.CharField(choices=[('M', 'Jongen'), ('F', 'Meisje')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='groepsmaatje',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='groepsmaatje_school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='heeft_betaald',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='klas',
            field=models.CharField(choices=[('1', 'Groep 1'), ('2', 'Groep 2'), ('3', 'Groep 3'), ('4', 'Groep 4'), ('5', 'Groep 5'), ('6', 'Groep 6'), ('7', 'Groep 7'), ('8', 'Groep 8')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='overnachting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='school',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='tel1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='voornaam',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aanmelding',
            name='woonplaats',
            field=models.CharField(max_length=100),
        ),
    ]
