# Generated by Django 3.2 on 2025-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0016_aanmelding_normaal_niet_corona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aanmelding',
            name='heeft_betaald',
        ),
        migrations.AddField(
            model_name='aanmelding',
            name='organisatie',
            field=models.BooleanField(default=False),
        ),
    ]
