# Generated by Django 3.2 on 2026-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0017_auto_20250504_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='dag',
            name='volgorde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taak',
            name='volgorde',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
