# Generated by Django 3.2 on 2026-05-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0018_auto_20260510_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dag',
            options={'ordering': ('volgorde',), 'verbose_name_plural': 'Dagen'},
        ),
        migrations.AlterModelOptions(
            name='taak',
            options={'ordering': ['volgorde'], 'verbose_name_plural': 'Taken'},
        ),
        migrations.RemoveField(
            model_name='aanmelding',
            name='organisatie',
        ),
    ]
