# Generated by Django 3.2 on 2026-05-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvs', '0019_auto_20260510_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrijwilliger',
            name='stage',
        ),
    ]
