# Generated by Django 5.2.18 on 2026-10-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
        ('mvs', '0020_remove_vrijwilliger_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorextension',
            name='public_extension',
        ),
        migrations.AlterField(
            model_name='sidebox',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
